#ifndef variables_h
#define variables_h

// Abs variables
Float_t         TauC_Inc_0j_EnergyWgt_jesup_Abs, TauB_Inc_0j_pTWgt_jesup_Abs, TauC_Inc_0j_EnergyWgt_jesdn_Abs, TauB_Inc_0j_pTWgt_jesdn_Abs;
int jet1index_jesup_Abs, jet2index_jesup_Abs, jet1index2p5_jesup_Abs, jet2index2p5_jesup_Abs, jet1pt_jesup_Abs, jet2pt_jesup_Abs, jet1pt2p5_jesup_Abs, jet2pt2p5_jesup_Abs, njets_pt30_eta4p7_jesup_Abs, njets_pt30_eta2p5_jesup_Abs, njets_pt30_eta4p7_jesdn_Abs, njets_pt30_eta2p5_jesdn_Abs;
int jet1index_jesdn_Abs, jet2index_jesdn_Abs, jet1index2p5_jesdn_Abs, jet2index2p5_jesdn_Abs, jet1pt_jesdn_Abs, jet2pt_jesdn_Abs, jet1pt2p5_jesdn_Abs, jet2pt2p5_jesdn_Abs;

float pTj1_jesup_Abs, pt_leadingjet_pt30_eta4p7_jesup_Abs, pTj2_jesup_Abs, etaj1_jesup_Abs, etaj2_jesup_Abs, pTj1_2p5_jesup_Abs, pt_leadingjet_pt30_eta2p5_jesup_Abs, pTj2_2p5_jesup_Abs, mj1j2_jesup_Abs, dEtaj1j2_jesup_Abs, yj1_jesup_Abs, yj2_jesup_Abs, mass4lj_jesup_Abs, pT4lj_jesup_Abs, mass4ljj_jesup_Abs, pT4ljj_jesup_Abs, dPhiHj1_jesup_Abs, dyHj1_jesup_Abs, dPhij1j2_jesup_Abs, dPhiHj1j2_jesup_Abs, yj1_2p5_jesup_Abs, yj2_2p5_jesup_Abs, mass4lj_2p5_jesup_Abs, pT4lj_2p5_jesup_Abs, mass4ljj_2p5_jesup_Abs, pT4ljj_2p5_jesup_Abs, dPhiHj1_2p5_jesup_Abs, dyHj1_2p5_jesup_Abs, mj1j2_2p5_jesup_Abs, dEtaj1j2_2p5_jesup_Abs, dPhij1j2_2p5_jesup_Abs, dPhiHj1j2_2p5_jesup_Abs, etaj2_2p5_jesup_Abs;

float pTj1_jesdn_Abs, pt_leadingjet_pt30_eta4p7_jesdn_Abs, pTj2_jesdn_Abs,etaj1_jesdn_Abs, etaj2_jesdn_Abs, pTj1_2p5_jesdn_Abs, pt_leadingjet_pt30_eta2p5_jesdn_Abs, pTj2_2p5_jesdn_Abs, mj1j2_jesdn_Abs, dEtaj1j2_jesdn_Abs, yj1_jesdn_Abs, yj2_jesdn_Abs, dPhiHj1_jesdn_Abs, dyHj1_jesdn_Abs, dPhij1j2_jesdn_Abs, dPhiHj1j2_jesdn_Abs, yj1_2p5_jesdn_Abs, yj2_2p5_jesdn_Abs, dPhiHj1_2p5_jesdn_Abs, dyHj1_2p5_jesdn_Abs, mj1j2_2p5_jesdn_Abs, dEtaj1j2_2p5_jesdn_Abs, dPhij1j2_2p5_jesdn_Abs, dPhiHj1j2_2p5_jesdn_Abs, mass4lj_jesdn_Abs, pT4lj_jesdn_Abs, mass4ljj_jesdn_Abs, pT4ljj_jesdn_Abs, mass4lj_2p5_jesdn_Abs, pT4lj_2p5_jesdn_Abs, mass4ljj_2p5_jesdn_Abs, pT4ljj_2p5_jesdn_Abs, etaj2_2p5_jesdn_Abs;

///////////////////////////////////////////////////////////////////////
// Abs_year variables
Float_t         TauC_Inc_0j_EnergyWgt_jesup_Abs_year, TauB_Inc_0j_pTWgt_jesup_Abs_year, TauC_Inc_0j_EnergyWgt_jesdn_Abs_year, TauB_Inc_0j_pTWgt_jesdn_Abs_year;
int jet1index_jesup_Abs_year, jet2index_jesup_Abs_year, jet1index2p5_jesup_Abs_year, jet2index2p5_jesup_Abs_year, jet1pt_jesup_Abs_year, jet2pt_jesup_Abs_year, jet1pt2p5_jesup_Abs_year, jet2pt2p5_jesup_Abs_year, njets_pt30_eta4p7_jesup_Abs_year, njets_pt30_eta2p5_jesup_Abs_year, njets_pt30_eta4p7_jesdn_Abs_year, njets_pt30_eta2p5_jesdn_Abs_year;
int jet1index_jesdn_Abs_year, jet2index_jesdn_Abs_year, jet1index2p5_jesdn_Abs_year, jet2index2p5_jesdn_Abs_year, jet1pt_jesdn_Abs_year, jet2pt_jesdn_Abs_year, jet1pt2p5_jesdn_Abs_year, jet2pt2p5_jesdn_Abs_year;

float pTj1_jesup_Abs_year, pt_leadingjet_pt30_eta4p7_jesup_Abs_year, pTj2_jesup_Abs_year, etaj1_jesup_Abs_year, etaj2_jesup_Abs_year, pTj1_2p5_jesup_Abs_year, pt_leadingjet_pt30_eta2p5_jesup_Abs_year, pTj2_2p5_jesup_Abs_year, mj1j2_jesup_Abs_year, dEtaj1j2_jesup_Abs_year, yj1_jesup_Abs_year, yj2_jesup_Abs_year, mass4lj_jesup_Abs_year, pT4lj_jesup_Abs_year, mass4ljj_jesup_Abs_year, pT4ljj_jesup_Abs_year, dPhiHj1_jesup_Abs_year, dyHj1_jesup_Abs_year, dPhij1j2_jesup_Abs_year, dPhiHj1j2_jesup_Abs_year, yj1_2p5_jesup_Abs_year, yj2_2p5_jesup_Abs_year, mass4lj_2p5_jesup_Abs_year, pT4lj_2p5_jesup_Abs_year, mass4ljj_2p5_jesup_Abs_year, pT4ljj_2p5_jesup_Abs_year, dPhiHj1_2p5_jesup_Abs_year, dyHj1_2p5_jesup_Abs_year, mj1j2_2p5_jesup_Abs_year, dEtaj1j2_2p5_jesup_Abs_year, dPhij1j2_2p5_jesup_Abs_year, dPhiHj1j2_2p5_jesup_Abs_year, etaj2_2p5_jesup_Abs_year;

float pTj1_jesdn_Abs_year, pt_leadingjet_pt30_eta4p7_jesdn_Abs_year, pTj2_jesdn_Abs_year,etaj1_jesdn_Abs_year, etaj2_jesdn_Abs_year, pTj1_2p5_jesdn_Abs_year, pt_leadingjet_pt30_eta2p5_jesdn_Abs_year, pTj2_2p5_jesdn_Abs_year, mj1j2_jesdn_Abs_year, dEtaj1j2_jesdn_Abs_year, yj1_jesdn_Abs_year, yj2_jesdn_Abs_year, dPhiHj1_jesdn_Abs_year, dyHj1_jesdn_Abs_year, dPhij1j2_jesdn_Abs_year, dPhiHj1j2_jesdn_Abs_year, yj1_2p5_jesdn_Abs_year, yj2_2p5_jesdn_Abs_year, dPhiHj1_2p5_jesdn_Abs_year, dyHj1_2p5_jesdn_Abs_year, mj1j2_2p5_jesdn_Abs_year, dEtaj1j2_2p5_jesdn_Abs_year, dPhij1j2_2p5_jesdn_Abs_year, dPhiHj1j2_2p5_jesdn_Abs_year, mass4lj_jesdn_Abs_year, pT4lj_jesdn_Abs_year, mass4ljj_jesdn_Abs_year, pT4ljj_jesdn_Abs_year, mass4lj_2p5_jesdn_Abs_year, pT4lj_2p5_jesdn_Abs_year, mass4ljj_2p5_jesdn_Abs_year, pT4ljj_2p5_jesdn_Abs_year, etaj2_2p5_jesdn_Abs_year;


///////////////////////////////////////////////////////////////////////
// BBEC1 variables
Float_t         TauC_Inc_0j_EnergyWgt_jesup_BBEC1, TauB_Inc_0j_pTWgt_jesup_BBEC1, TauC_Inc_0j_EnergyWgt_jesdn_BBEC1, TauB_Inc_0j_pTWgt_jesdn_BBEC1;
int jet1index_jesup_BBEC1, jet2index_jesup_BBEC1, jet1index2p5_jesup_BBEC1, jet2index2p5_jesup_BBEC1, jet1pt_jesup_BBEC1, jet2pt_jesup_BBEC1, jet1pt2p5_jesup_BBEC1, jet2pt2p5_jesup_BBEC1, njets_pt30_eta4p7_jesup_BBEC1, njets_pt30_eta2p5_jesup_BBEC1, njets_pt30_eta4p7_jesdn_BBEC1, njets_pt30_eta2p5_jesdn_BBEC1;
int jet1index_jesdn_BBEC1, jet2index_jesdn_BBEC1, jet1index2p5_jesdn_BBEC1, jet2index2p5_jesdn_BBEC1, jet1pt_jesdn_BBEC1, jet2pt_jesdn_BBEC1, jet1pt2p5_jesdn_BBEC1, jet2pt2p5_jesdn_BBEC1;

float pTj1_jesup_BBEC1, pt_leadingjet_pt30_eta4p7_jesup_BBEC1, pTj2_jesup_BBEC1, etaj1_jesup_BBEC1, etaj2_jesup_BBEC1, pTj1_2p5_jesup_BBEC1, pt_leadingjet_pt30_eta2p5_jesup_BBEC1, pTj2_2p5_jesup_BBEC1, mj1j2_jesup_BBEC1, dEtaj1j2_jesup_BBEC1, yj1_jesup_BBEC1, yj2_jesup_BBEC1, mass4lj_jesup_BBEC1, pT4lj_jesup_BBEC1, mass4ljj_jesup_BBEC1, pT4ljj_jesup_BBEC1, dPhiHj1_jesup_BBEC1, dyHj1_jesup_BBEC1, dPhij1j2_jesup_BBEC1, dPhiHj1j2_jesup_BBEC1, yj1_2p5_jesup_BBEC1, yj2_2p5_jesup_BBEC1, mass4lj_2p5_jesup_BBEC1, pT4lj_2p5_jesup_BBEC1, mass4ljj_2p5_jesup_BBEC1, pT4ljj_2p5_jesup_BBEC1, dPhiHj1_2p5_jesup_BBEC1, dyHj1_2p5_jesup_BBEC1, mj1j2_2p5_jesup_BBEC1, dEtaj1j2_2p5_jesup_BBEC1, dPhij1j2_2p5_jesup_BBEC1, dPhiHj1j2_2p5_jesup_BBEC1, etaj2_2p5_jesup_BBEC1;

float pTj1_jesdn_BBEC1, pt_leadingjet_pt30_eta4p7_jesdn_BBEC1, pTj2_jesdn_BBEC1,etaj1_jesdn_BBEC1, etaj2_jesdn_BBEC1, pTj1_2p5_jesdn_BBEC1, pt_leadingjet_pt30_eta2p5_jesdn_BBEC1, pTj2_2p5_jesdn_BBEC1, mj1j2_jesdn_BBEC1, dEtaj1j2_jesdn_BBEC1, yj1_jesdn_BBEC1, yj2_jesdn_BBEC1, dPhiHj1_jesdn_BBEC1, dyHj1_jesdn_BBEC1, dPhij1j2_jesdn_BBEC1, dPhiHj1j2_jesdn_BBEC1, yj1_2p5_jesdn_BBEC1, yj2_2p5_jesdn_BBEC1, dPhiHj1_2p5_jesdn_BBEC1, dyHj1_2p5_jesdn_BBEC1, mj1j2_2p5_jesdn_BBEC1, dEtaj1j2_2p5_jesdn_BBEC1, dPhij1j2_2p5_jesdn_BBEC1, dPhiHj1j2_2p5_jesdn_BBEC1, mass4lj_jesdn_BBEC1, pT4lj_jesdn_BBEC1, mass4ljj_jesdn_BBEC1, pT4ljj_jesdn_BBEC1, mass4lj_2p5_jesdn_BBEC1, pT4lj_2p5_jesdn_BBEC1, mass4ljj_2p5_jesdn_BBEC1, pT4ljj_2p5_jesdn_BBEC1, etaj2_2p5_jesdn_BBEC1;

///////////////////////////////////////////////////////////////////////
// BBEC1_year variables
Float_t         TauC_Inc_0j_EnergyWgt_jesup_BBEC1_year, TauB_Inc_0j_pTWgt_jesup_BBEC1_year, TauC_Inc_0j_EnergyWgt_jesdn_BBEC1_year, TauB_Inc_0j_pTWgt_jesdn_BBEC1_year;
int jet1index_jesup_BBEC1_year, jet2index_jesup_BBEC1_year, jet1index2p5_jesup_BBEC1_year, jet2index2p5_jesup_BBEC1_year, jet1pt_jesup_BBEC1_year, jet2pt_jesup_BBEC1_year, jet1pt2p5_jesup_BBEC1_year, jet2pt2p5_jesup_BBEC1_year, njets_pt30_eta4p7_jesup_BBEC1_year, njets_pt30_eta2p5_jesup_BBEC1_year, njets_pt30_eta4p7_jesdn_BBEC1_year, njets_pt30_eta2p5_jesdn_BBEC1_year;
int jet1index_jesdn_BBEC1_year, jet2index_jesdn_BBEC1_year, jet1index2p5_jesdn_BBEC1_year, jet2index2p5_jesdn_BBEC1_year, jet1pt_jesdn_BBEC1_year, jet2pt_jesdn_BBEC1_year, jet1pt2p5_jesdn_BBEC1_year, jet2pt2p5_jesdn_BBEC1_year;

float pTj1_jesup_BBEC1_year, pt_leadingjet_pt30_eta4p7_jesup_BBEC1_year, pTj2_jesup_BBEC1_year, etaj1_jesup_BBEC1_year, etaj2_jesup_BBEC1_year, pTj1_2p5_jesup_BBEC1_year, pt_leadingjet_pt30_eta2p5_jesup_BBEC1_year, pTj2_2p5_jesup_BBEC1_year, mj1j2_jesup_BBEC1_year, dEtaj1j2_jesup_BBEC1_year, yj1_jesup_BBEC1_year, yj2_jesup_BBEC1_year, mass4lj_jesup_BBEC1_year, pT4lj_jesup_BBEC1_year, mass4ljj_jesup_BBEC1_year, pT4ljj_jesup_BBEC1_year, dPhiHj1_jesup_BBEC1_year, dyHj1_jesup_BBEC1_year, dPhij1j2_jesup_BBEC1_year, dPhiHj1j2_jesup_BBEC1_year, yj1_2p5_jesup_BBEC1_year, yj2_2p5_jesup_BBEC1_year, mass4lj_2p5_jesup_BBEC1_year, pT4lj_2p5_jesup_BBEC1_year, mass4ljj_2p5_jesup_BBEC1_year, pT4ljj_2p5_jesup_BBEC1_year, dPhiHj1_2p5_jesup_BBEC1_year, dyHj1_2p5_jesup_BBEC1_year, mj1j2_2p5_jesup_BBEC1_year, dEtaj1j2_2p5_jesup_BBEC1_year, dPhij1j2_2p5_jesup_BBEC1_year, dPhiHj1j2_2p5_jesup_BBEC1_year, etaj2_2p5_jesup_BBEC1_year;

float pTj1_jesdn_BBEC1_year, pt_leadingjet_pt30_eta4p7_jesdn_BBEC1_year, pTj2_jesdn_BBEC1_year,etaj1_jesdn_BBEC1_year, etaj2_jesdn_BBEC1_year, pTj1_2p5_jesdn_BBEC1_year, pt_leadingjet_pt30_eta2p5_jesdn_BBEC1_year, pTj2_2p5_jesdn_BBEC1_year, mj1j2_jesdn_BBEC1_year, dEtaj1j2_jesdn_BBEC1_year, yj1_jesdn_BBEC1_year, yj2_jesdn_BBEC1_year, dPhiHj1_jesdn_BBEC1_year, dyHj1_jesdn_BBEC1_year, dPhij1j2_jesdn_BBEC1_year, dPhiHj1j2_jesdn_BBEC1_year, yj1_2p5_jesdn_BBEC1_year, yj2_2p5_jesdn_BBEC1_year, dPhiHj1_2p5_jesdn_BBEC1_year, dyHj1_2p5_jesdn_BBEC1_year, mj1j2_2p5_jesdn_BBEC1_year, dEtaj1j2_2p5_jesdn_BBEC1_year, dPhij1j2_2p5_jesdn_BBEC1_year, dPhiHj1j2_2p5_jesdn_BBEC1_year, mass4lj_jesdn_BBEC1_year, pT4lj_jesdn_BBEC1_year, mass4ljj_jesdn_BBEC1_year, pT4ljj_jesdn_BBEC1_year, mass4lj_2p5_jesdn_BBEC1_year, pT4lj_2p5_jesdn_BBEC1_year, mass4ljj_2p5_jesdn_BBEC1_year, pT4ljj_2p5_jesdn_BBEC1_year, etaj2_2p5_jesdn_BBEC1_year;


///////////////////////////////////////////////////////////////////////
// EC2 variables
Float_t         TauC_Inc_0j_EnergyWgt_jesup_EC2, TauB_Inc_0j_pTWgt_jesup_EC2, TauC_Inc_0j_EnergyWgt_jesdn_EC2, TauB_Inc_0j_pTWgt_jesdn_EC2;
int jet1index_jesup_EC2, jet2index_jesup_EC2, jet1index2p5_jesup_EC2, jet2index2p5_jesup_EC2, jet1pt_jesup_EC2, jet2pt_jesup_EC2, jet1pt2p5_jesup_EC2, jet2pt2p5_jesup_EC2, njets_pt30_eta4p7_jesup_EC2, njets_pt30_eta2p5_jesup_EC2, njets_pt30_eta4p7_jesdn_EC2, njets_pt30_eta2p5_jesdn_EC2;
int jet1index_jesdn_EC2, jet2index_jesdn_EC2, jet1index2p5_jesdn_EC2, jet2index2p5_jesdn_EC2, jet1pt_jesdn_EC2, jet2pt_jesdn_EC2, jet1pt2p5_jesdn_EC2, jet2pt2p5_jesdn_EC2;

float pTj1_jesup_EC2, pt_leadingjet_pt30_eta4p7_jesup_EC2, pTj2_jesup_EC2, etaj1_jesup_EC2, etaj2_jesup_EC2, pTj1_2p5_jesup_EC2, pt_leadingjet_pt30_eta2p5_jesup_EC2, pTj2_2p5_jesup_EC2, mj1j2_jesup_EC2, dEtaj1j2_jesup_EC2, yj1_jesup_EC2, yj2_jesup_EC2, mass4lj_jesup_EC2, pT4lj_jesup_EC2, mass4ljj_jesup_EC2, pT4ljj_jesup_EC2, dPhiHj1_jesup_EC2, dyHj1_jesup_EC2, dPhij1j2_jesup_EC2, dPhiHj1j2_jesup_EC2, yj1_2p5_jesup_EC2, yj2_2p5_jesup_EC2, mass4lj_2p5_jesup_EC2, pT4lj_2p5_jesup_EC2, mass4ljj_2p5_jesup_EC2, pT4ljj_2p5_jesup_EC2, dPhiHj1_2p5_jesup_EC2, dyHj1_2p5_jesup_EC2, mj1j2_2p5_jesup_EC2, dEtaj1j2_2p5_jesup_EC2, dPhij1j2_2p5_jesup_EC2, dPhiHj1j2_2p5_jesup_EC2, etaj2_2p5_jesup_EC2;

float pTj1_jesdn_EC2, pt_leadingjet_pt30_eta4p7_jesdn_EC2, pTj2_jesdn_EC2,etaj1_jesdn_EC2, etaj2_jesdn_EC2, pTj1_2p5_jesdn_EC2, pt_leadingjet_pt30_eta2p5_jesdn_EC2, pTj2_2p5_jesdn_EC2, mj1j2_jesdn_EC2, dEtaj1j2_jesdn_EC2, yj1_jesdn_EC2, yj2_jesdn_EC2, dPhiHj1_jesdn_EC2, dyHj1_jesdn_EC2, dPhij1j2_jesdn_EC2, dPhiHj1j2_jesdn_EC2, yj1_2p5_jesdn_EC2, yj2_2p5_jesdn_EC2, dPhiHj1_2p5_jesdn_EC2, dyHj1_2p5_jesdn_EC2, mj1j2_2p5_jesdn_EC2, dEtaj1j2_2p5_jesdn_EC2, dPhij1j2_2p5_jesdn_EC2, dPhiHj1j2_2p5_jesdn_EC2, mass4lj_jesdn_EC2, pT4lj_jesdn_EC2, mass4ljj_jesdn_EC2, pT4ljj_jesdn_EC2, mass4lj_2p5_jesdn_EC2, pT4lj_2p5_jesdn_EC2, mass4ljj_2p5_jesdn_EC2, pT4ljj_2p5_jesdn_EC2, etaj2_2p5_jesdn_EC2;



///////////////////////////////////////////////////////////////////////
// EC2_year variables
Float_t         TauC_Inc_0j_EnergyWgt_jesup_EC2_year, TauB_Inc_0j_pTWgt_jesup_EC2_year, TauC_Inc_0j_EnergyWgt_jesdn_EC2_year, TauB_Inc_0j_pTWgt_jesdn_EC2_year;
int jet1index_jesup_EC2_year, jet2index_jesup_EC2_year, jet1index2p5_jesup_EC2_year, jet2index2p5_jesup_EC2_year, jet1pt_jesup_EC2_year, jet2pt_jesup_EC2_year, jet1pt2p5_jesup_EC2_year, jet2pt2p5_jesup_EC2_year, njets_pt30_eta4p7_jesup_EC2_year, njets_pt30_eta2p5_jesup_EC2_year, njets_pt30_eta4p7_jesdn_EC2_year, njets_pt30_eta2p5_jesdn_EC2_year;
int jet1index_jesdn_EC2_year, jet2index_jesdn_EC2_year, jet1index2p5_jesdn_EC2_year, jet2index2p5_jesdn_EC2_year, jet1pt_jesdn_EC2_year, jet2pt_jesdn_EC2_year, jet1pt2p5_jesdn_EC2_year, jet2pt2p5_jesdn_EC2_year;

float pTj1_jesup_EC2_year, pt_leadingjet_pt30_eta4p7_jesup_EC2_year, pTj2_jesup_EC2_year, etaj1_jesup_EC2_year, etaj2_jesup_EC2_year, pTj1_2p5_jesup_EC2_year, pt_leadingjet_pt30_eta2p5_jesup_EC2_year, pTj2_2p5_jesup_EC2_year, mj1j2_jesup_EC2_year, dEtaj1j2_jesup_EC2_year, yj1_jesup_EC2_year, yj2_jesup_EC2_year, mass4lj_jesup_EC2_year, pT4lj_jesup_EC2_year, mass4ljj_jesup_EC2_year, pT4ljj_jesup_EC2_year, dPhiHj1_jesup_EC2_year, dyHj1_jesup_EC2_year, dPhij1j2_jesup_EC2_year, dPhiHj1j2_jesup_EC2_year, yj1_2p5_jesup_EC2_year, yj2_2p5_jesup_EC2_year, mass4lj_2p5_jesup_EC2_year, pT4lj_2p5_jesup_EC2_year, mass4ljj_2p5_jesup_EC2_year, pT4ljj_2p5_jesup_EC2_year, dPhiHj1_2p5_jesup_EC2_year, dyHj1_2p5_jesup_EC2_year, mj1j2_2p5_jesup_EC2_year, dEtaj1j2_2p5_jesup_EC2_year, dPhij1j2_2p5_jesup_EC2_year, dPhiHj1j2_2p5_jesup_EC2_year, etaj2_2p5_jesup_EC2_year;

float pTj1_jesdn_EC2_year, pt_leadingjet_pt30_eta4p7_jesdn_EC2_year, pTj2_jesdn_EC2_year,etaj1_jesdn_EC2_year, etaj2_jesdn_EC2_year, pTj1_2p5_jesdn_EC2_year, pt_leadingjet_pt30_eta2p5_jesdn_EC2_year, pTj2_2p5_jesdn_EC2_year, mj1j2_jesdn_EC2_year, dEtaj1j2_jesdn_EC2_year, yj1_jesdn_EC2_year, yj2_jesdn_EC2_year, dPhiHj1_jesdn_EC2_year, dyHj1_jesdn_EC2_year, dPhij1j2_jesdn_EC2_year, dPhiHj1j2_jesdn_EC2_year, yj1_2p5_jesdn_EC2_year, yj2_2p5_jesdn_EC2_year, dPhiHj1_2p5_jesdn_EC2_year, dyHj1_2p5_jesdn_EC2_year, mj1j2_2p5_jesdn_EC2_year, dEtaj1j2_2p5_jesdn_EC2_year, dPhij1j2_2p5_jesdn_EC2_year, dPhiHj1j2_2p5_jesdn_EC2_year, mass4lj_jesdn_EC2_year, pT4lj_jesdn_EC2_year, mass4ljj_jesdn_EC2_year, pT4ljj_jesdn_EC2_year, mass4lj_2p5_jesdn_EC2_year, pT4lj_2p5_jesdn_EC2_year, mass4ljj_2p5_jesdn_EC2_year, pT4ljj_2p5_jesdn_EC2_year, etaj2_2p5_jesdn_EC2_year;


///////////////////////////////////////////////////////////////////////
// FlavQCD variables
Float_t         TauC_Inc_0j_EnergyWgt_jesup_FlavQCD, TauB_Inc_0j_pTWgt_jesup_FlavQCD, TauC_Inc_0j_EnergyWgt_jesdn_FlavQCD, TauB_Inc_0j_pTWgt_jesdn_FlavQCD;
int jet1index_jesup_FlavQCD, jet2index_jesup_FlavQCD, jet1index2p5_jesup_FlavQCD, jet2index2p5_jesup_FlavQCD, jet1pt_jesup_FlavQCD, jet2pt_jesup_FlavQCD, jet1pt2p5_jesup_FlavQCD, jet2pt2p5_jesup_FlavQCD, njets_pt30_eta4p7_jesup_FlavQCD, njets_pt30_eta2p5_jesup_FlavQCD, njets_pt30_eta4p7_jesdn_FlavQCD, njets_pt30_eta2p5_jesdn_FlavQCD;
int jet1index_jesdn_FlavQCD, jet2index_jesdn_FlavQCD, jet1index2p5_jesdn_FlavQCD, jet2index2p5_jesdn_FlavQCD, jet1pt_jesdn_FlavQCD, jet2pt_jesdn_FlavQCD, jet1pt2p5_jesdn_FlavQCD, jet2pt2p5_jesdn_FlavQCD;

float pTj1_jesup_FlavQCD, pt_leadingjet_pt30_eta4p7_jesup_FlavQCD, pTj2_jesup_FlavQCD, etaj1_jesup_FlavQCD, etaj2_jesup_FlavQCD, pTj1_2p5_jesup_FlavQCD, pt_leadingjet_pt30_eta2p5_jesup_FlavQCD, pTj2_2p5_jesup_FlavQCD, mj1j2_jesup_FlavQCD, dEtaj1j2_jesup_FlavQCD, yj1_jesup_FlavQCD, yj2_jesup_FlavQCD, mass4lj_jesup_FlavQCD, pT4lj_jesup_FlavQCD, mass4ljj_jesup_FlavQCD, pT4ljj_jesup_FlavQCD, dPhiHj1_jesup_FlavQCD, dyHj1_jesup_FlavQCD, dPhij1j2_jesup_FlavQCD, dPhiHj1j2_jesup_FlavQCD, yj1_2p5_jesup_FlavQCD, yj2_2p5_jesup_FlavQCD, mass4lj_2p5_jesup_FlavQCD, pT4lj_2p5_jesup_FlavQCD, mass4ljj_2p5_jesup_FlavQCD, pT4ljj_2p5_jesup_FlavQCD, dPhiHj1_2p5_jesup_FlavQCD, dyHj1_2p5_jesup_FlavQCD, mj1j2_2p5_jesup_FlavQCD, dEtaj1j2_2p5_jesup_FlavQCD, dPhij1j2_2p5_jesup_FlavQCD, dPhiHj1j2_2p5_jesup_FlavQCD, etaj2_2p5_jesup_FlavQCD;

float pTj1_jesdn_FlavQCD, pt_leadingjet_pt30_eta4p7_jesdn_FlavQCD, pTj2_jesdn_FlavQCD,etaj1_jesdn_FlavQCD, etaj2_jesdn_FlavQCD, pTj1_2p5_jesdn_FlavQCD, pt_leadingjet_pt30_eta2p5_jesdn_FlavQCD, pTj2_2p5_jesdn_FlavQCD, mj1j2_jesdn_FlavQCD, dEtaj1j2_jesdn_FlavQCD, yj1_jesdn_FlavQCD, yj2_jesdn_FlavQCD, dPhiHj1_jesdn_FlavQCD, dyHj1_jesdn_FlavQCD, dPhij1j2_jesdn_FlavQCD, dPhiHj1j2_jesdn_FlavQCD, yj1_2p5_jesdn_FlavQCD, yj2_2p5_jesdn_FlavQCD, dPhiHj1_2p5_jesdn_FlavQCD, dyHj1_2p5_jesdn_FlavQCD, mj1j2_2p5_jesdn_FlavQCD, dEtaj1j2_2p5_jesdn_FlavQCD, dPhij1j2_2p5_jesdn_FlavQCD, dPhiHj1j2_2p5_jesdn_FlavQCD, mass4lj_jesdn_FlavQCD, pT4lj_jesdn_FlavQCD, mass4ljj_jesdn_FlavQCD, pT4ljj_jesdn_FlavQCD, mass4lj_2p5_jesdn_FlavQCD, pT4lj_2p5_jesdn_FlavQCD, mass4ljj_2p5_jesdn_FlavQCD, pT4ljj_2p5_jesdn_FlavQCD, etaj2_2p5_jesdn_FlavQCD;



///////////////////////////////////////////////////////////////////////
// HF variables
Float_t         TauC_Inc_0j_EnergyWgt_jesup_HF, TauB_Inc_0j_pTWgt_jesup_HF, TauC_Inc_0j_EnergyWgt_jesdn_HF, TauB_Inc_0j_pTWgt_jesdn_HF;
int jet1index_jesup_HF, jet2index_jesup_HF, jet1index2p5_jesup_HF, jet2index2p5_jesup_HF, jet1pt_jesup_HF, jet2pt_jesup_HF, jet1pt2p5_jesup_HF, jet2pt2p5_jesup_HF, njets_pt30_eta4p7_jesup_HF, njets_pt30_eta2p5_jesup_HF, njets_pt30_eta4p7_jesdn_HF, njets_pt30_eta2p5_jesdn_HF;
int jet1index_jesdn_HF, jet2index_jesdn_HF, jet1index2p5_jesdn_HF, jet2index2p5_jesdn_HF, jet1pt_jesdn_HF, jet2pt_jesdn_HF, jet1pt2p5_jesdn_HF, jet2pt2p5_jesdn_HF;

float pTj1_jesup_HF, pt_leadingjet_pt30_eta4p7_jesup_HF, pTj2_jesup_HF, etaj1_jesup_HF, etaj2_jesup_HF, pTj1_2p5_jesup_HF, pt_leadingjet_pt30_eta2p5_jesup_HF, pTj2_2p5_jesup_HF, mj1j2_jesup_HF, dEtaj1j2_jesup_HF, yj1_jesup_HF, yj2_jesup_HF, mass4lj_jesup_HF, pT4lj_jesup_HF, mass4ljj_jesup_HF, pT4ljj_jesup_HF, dPhiHj1_jesup_HF, dyHj1_jesup_HF, dPhij1j2_jesup_HF, dPhiHj1j2_jesup_HF, yj1_2p5_jesup_HF, yj2_2p5_jesup_HF, mass4lj_2p5_jesup_HF, pT4lj_2p5_jesup_HF, mass4ljj_2p5_jesup_HF, pT4ljj_2p5_jesup_HF, dPhiHj1_2p5_jesup_HF, dyHj1_2p5_jesup_HF, mj1j2_2p5_jesup_HF, dEtaj1j2_2p5_jesup_HF, dPhij1j2_2p5_jesup_HF, dPhiHj1j2_2p5_jesup_HF, etaj2_2p5_jesup_HF;

float pTj1_jesdn_HF, pt_leadingjet_pt30_eta4p7_jesdn_HF, pTj2_jesdn_HF,etaj1_jesdn_HF, etaj2_jesdn_HF, pTj1_2p5_jesdn_HF, pt_leadingjet_pt30_eta2p5_jesdn_HF, pTj2_2p5_jesdn_HF, mj1j2_jesdn_HF, dEtaj1j2_jesdn_HF, yj1_jesdn_HF, yj2_jesdn_HF, dPhiHj1_jesdn_HF, dyHj1_jesdn_HF, dPhij1j2_jesdn_HF, dPhiHj1j2_jesdn_HF, yj1_2p5_jesdn_HF, yj2_2p5_jesdn_HF, dPhiHj1_2p5_jesdn_HF, dyHj1_2p5_jesdn_HF, mj1j2_2p5_jesdn_HF, dEtaj1j2_2p5_jesdn_HF, dPhij1j2_2p5_jesdn_HF, dPhiHj1j2_2p5_jesdn_HF, mass4lj_jesdn_HF, pT4lj_jesdn_HF, mass4ljj_jesdn_HF, pT4ljj_jesdn_HF, mass4lj_2p5_jesdn_HF, pT4lj_2p5_jesdn_HF, mass4ljj_2p5_jesdn_HF, pT4ljj_2p5_jesdn_HF, etaj2_2p5_jesdn_HF;



///////////////////////////////////////////////////////////////////////
// HF_year variables
Float_t         TauC_Inc_0j_EnergyWgt_jesup_HF_year, TauB_Inc_0j_pTWgt_jesup_HF_year, TauC_Inc_0j_EnergyWgt_jesdn_HF_year, TauB_Inc_0j_pTWgt_jesdn_HF_year;
int jet1index_jesup_HF_year, jet2index_jesup_HF_year, jet1index2p5_jesup_HF_year, jet2index2p5_jesup_HF_year, jet1pt_jesup_HF_year, jet2pt_jesup_HF_year, jet1pt2p5_jesup_HF_year, jet2pt2p5_jesup_HF_year, njets_pt30_eta4p7_jesup_HF_year, njets_pt30_eta2p5_jesup_HF_year, njets_pt30_eta4p7_jesdn_HF_year, njets_pt30_eta2p5_jesdn_HF_year;
int jet1index_jesdn_HF_year, jet2index_jesdn_HF_year, jet1index2p5_jesdn_HF_year, jet2index2p5_jesdn_HF_year, jet1pt_jesdn_HF_year, jet2pt_jesdn_HF_year, jet1pt2p5_jesdn_HF_year, jet2pt2p5_jesdn_HF_year;

float pTj1_jesup_HF_year, pt_leadingjet_pt30_eta4p7_jesup_HF_year, pTj2_jesup_HF_year, etaj1_jesup_HF_year, etaj2_jesup_HF_year, pTj1_2p5_jesup_HF_year, pt_leadingjet_pt30_eta2p5_jesup_HF_year, pTj2_2p5_jesup_HF_year, mj1j2_jesup_HF_year, dEtaj1j2_jesup_HF_year, yj1_jesup_HF_year, yj2_jesup_HF_year, mass4lj_jesup_HF_year, pT4lj_jesup_HF_year, mass4ljj_jesup_HF_year, pT4ljj_jesup_HF_year, dPhiHj1_jesup_HF_year, dyHj1_jesup_HF_year, dPhij1j2_jesup_HF_year, dPhiHj1j2_jesup_HF_year, yj1_2p5_jesup_HF_year, yj2_2p5_jesup_HF_year, mass4lj_2p5_jesup_HF_year, pT4lj_2p5_jesup_HF_year, mass4ljj_2p5_jesup_HF_year, pT4ljj_2p5_jesup_HF_year, dPhiHj1_2p5_jesup_HF_year, dyHj1_2p5_jesup_HF_year, mj1j2_2p5_jesup_HF_year, dEtaj1j2_2p5_jesup_HF_year, dPhij1j2_2p5_jesup_HF_year, dPhiHj1j2_2p5_jesup_HF_year, etaj2_2p5_jesup_HF_year;

float pTj1_jesdn_HF_year, pt_leadingjet_pt30_eta4p7_jesdn_HF_year, pTj2_jesdn_HF_year,etaj1_jesdn_HF_year, etaj2_jesdn_HF_year, pTj1_2p5_jesdn_HF_year, pt_leadingjet_pt30_eta2p5_jesdn_HF_year, pTj2_2p5_jesdn_HF_year, mj1j2_jesdn_HF_year, dEtaj1j2_jesdn_HF_year, yj1_jesdn_HF_year, yj2_jesdn_HF_year, dPhiHj1_jesdn_HF_year, dyHj1_jesdn_HF_year, dPhij1j2_jesdn_HF_year, dPhiHj1j2_jesdn_HF_year, yj1_2p5_jesdn_HF_year, yj2_2p5_jesdn_HF_year, dPhiHj1_2p5_jesdn_HF_year, dyHj1_2p5_jesdn_HF_year, mj1j2_2p5_jesdn_HF_year, dEtaj1j2_2p5_jesdn_HF_year, dPhij1j2_2p5_jesdn_HF_year, dPhiHj1j2_2p5_jesdn_HF_year, mass4lj_jesdn_HF_year, pT4lj_jesdn_HF_year, mass4ljj_jesdn_HF_year, pT4ljj_jesdn_HF_year, mass4lj_2p5_jesdn_HF_year, pT4lj_2p5_jesdn_HF_year, mass4ljj_2p5_jesdn_HF_year, pT4ljj_2p5_jesdn_HF_year, etaj2_2p5_jesdn_HF_year;



///////////////////////////////////////////////////////////////////////
// RelBal variables
Float_t         TauC_Inc_0j_EnergyWgt_jesup_RelBal, TauB_Inc_0j_pTWgt_jesup_RelBal, TauC_Inc_0j_EnergyWgt_jesdn_RelBal, TauB_Inc_0j_pTWgt_jesdn_RelBal;
int jet1index_jesup_RelBal, jet2index_jesup_RelBal, jet1index2p5_jesup_RelBal, jet2index2p5_jesup_RelBal, jet1pt_jesup_RelBal, jet2pt_jesup_RelBal, jet1pt2p5_jesup_RelBal, jet2pt2p5_jesup_RelBal, njets_pt30_eta4p7_jesup_RelBal, njets_pt30_eta2p5_jesup_RelBal, njets_pt30_eta4p7_jesdn_RelBal, njets_pt30_eta2p5_jesdn_RelBal;
int jet1index_jesdn_RelBal, jet2index_jesdn_RelBal, jet1index2p5_jesdn_RelBal, jet2index2p5_jesdn_RelBal, jet1pt_jesdn_RelBal, jet2pt_jesdn_RelBal, jet1pt2p5_jesdn_RelBal, jet2pt2p5_jesdn_RelBal;

float pTj1_jesup_RelBal, pt_leadingjet_pt30_eta4p7_jesup_RelBal, pTj2_jesup_RelBal, etaj1_jesup_RelBal, etaj2_jesup_RelBal, pTj1_2p5_jesup_RelBal, pt_leadingjet_pt30_eta2p5_jesup_RelBal, pTj2_2p5_jesup_RelBal, mj1j2_jesup_RelBal, dEtaj1j2_jesup_RelBal, yj1_jesup_RelBal, yj2_jesup_RelBal, mass4lj_jesup_RelBal, pT4lj_jesup_RelBal, mass4ljj_jesup_RelBal, pT4ljj_jesup_RelBal, dPhiHj1_jesup_RelBal, dyHj1_jesup_RelBal, dPhij1j2_jesup_RelBal, dPhiHj1j2_jesup_RelBal, yj1_2p5_jesup_RelBal, yj2_2p5_jesup_RelBal, mass4lj_2p5_jesup_RelBal, pT4lj_2p5_jesup_RelBal, mass4ljj_2p5_jesup_RelBal, pT4ljj_2p5_jesup_RelBal, dPhiHj1_2p5_jesup_RelBal, dyHj1_2p5_jesup_RelBal, mj1j2_2p5_jesup_RelBal, dEtaj1j2_2p5_jesup_RelBal, dPhij1j2_2p5_jesup_RelBal, dPhiHj1j2_2p5_jesup_RelBal, etaj2_2p5_jesup_RelBal;

float pTj1_jesdn_RelBal, pt_leadingjet_pt30_eta4p7_jesdn_RelBal, pTj2_jesdn_RelBal,etaj1_jesdn_RelBal, etaj2_jesdn_RelBal, pTj1_2p5_jesdn_RelBal, pt_leadingjet_pt30_eta2p5_jesdn_RelBal, pTj2_2p5_jesdn_RelBal, mj1j2_jesdn_RelBal, dEtaj1j2_jesdn_RelBal, yj1_jesdn_RelBal, yj2_jesdn_RelBal, dPhiHj1_jesdn_RelBal, dyHj1_jesdn_RelBal, dPhij1j2_jesdn_RelBal, dPhiHj1j2_jesdn_RelBal, yj1_2p5_jesdn_RelBal, yj2_2p5_jesdn_RelBal, dPhiHj1_2p5_jesdn_RelBal, dyHj1_2p5_jesdn_RelBal, mj1j2_2p5_jesdn_RelBal, dEtaj1j2_2p5_jesdn_RelBal, dPhij1j2_2p5_jesdn_RelBal, dPhiHj1j2_2p5_jesdn_RelBal, mass4lj_jesdn_RelBal, pT4lj_jesdn_RelBal, mass4ljj_jesdn_RelBal, pT4ljj_jesdn_RelBal, mass4lj_2p5_jesdn_RelBal, pT4lj_2p5_jesdn_RelBal, mass4ljj_2p5_jesdn_RelBal, pT4ljj_2p5_jesdn_RelBal, etaj2_2p5_jesdn_RelBal;




///////////////////////////////////////////////////////////////////////
// RelSample_year variables
Float_t         TauC_Inc_0j_EnergyWgt_jesup_RelSample_year, TauB_Inc_0j_pTWgt_jesup_RelSample_year, TauC_Inc_0j_EnergyWgt_jesdn_RelSample_year, TauB_Inc_0j_pTWgt_jesdn_RelSample_year;
int jet1index_jesup_RelSample_year, jet2index_jesup_RelSample_year, jet1index2p5_jesup_RelSample_year, jet2index2p5_jesup_RelSample_year, jet1pt_jesup_RelSample_year, jet2pt_jesup_RelSample_year, jet1pt2p5_jesup_RelSample_year, jet2pt2p5_jesup_RelSample_year, njets_pt30_eta4p7_jesup_RelSample_year, njets_pt30_eta2p5_jesup_RelSample_year, njets_pt30_eta4p7_jesdn_RelSample_year, njets_pt30_eta2p5_jesdn_RelSample_year;
int jet1index_jesdn_RelSample_year, jet2index_jesdn_RelSample_year, jet1index2p5_jesdn_RelSample_year, jet2index2p5_jesdn_RelSample_year, jet1pt_jesdn_RelSample_year, jet2pt_jesdn_RelSample_year, jet1pt2p5_jesdn_RelSample_year, jet2pt2p5_jesdn_RelSample_year;

float pTj1_jesup_RelSample_year, pt_leadingjet_pt30_eta4p7_jesup_RelSample_year, pTj2_jesup_RelSample_year, etaj1_jesup_RelSample_year, etaj2_jesup_RelSample_year, pTj1_2p5_jesup_RelSample_year, pt_leadingjet_pt30_eta2p5_jesup_RelSample_year, pTj2_2p5_jesup_RelSample_year, mj1j2_jesup_RelSample_year, dEtaj1j2_jesup_RelSample_year, yj1_jesup_RelSample_year, yj2_jesup_RelSample_year, mass4lj_jesup_RelSample_year, pT4lj_jesup_RelSample_year, mass4ljj_jesup_RelSample_year, pT4ljj_jesup_RelSample_year, dPhiHj1_jesup_RelSample_year, dyHj1_jesup_RelSample_year, dPhij1j2_jesup_RelSample_year, dPhiHj1j2_jesup_RelSample_year, yj1_2p5_jesup_RelSample_year, yj2_2p5_jesup_RelSample_year, mass4lj_2p5_jesup_RelSample_year, pT4lj_2p5_jesup_RelSample_year, mass4ljj_2p5_jesup_RelSample_year, pT4ljj_2p5_jesup_RelSample_year, dPhiHj1_2p5_jesup_RelSample_year, dyHj1_2p5_jesup_RelSample_year, mj1j2_2p5_jesup_RelSample_year, dEtaj1j2_2p5_jesup_RelSample_year, dPhij1j2_2p5_jesup_RelSample_year, dPhiHj1j2_2p5_jesup_RelSample_year, etaj2_2p5_jesup_RelSample_year;

float pTj1_jesdn_RelSample_year, pt_leadingjet_pt30_eta4p7_jesdn_RelSample_year, pTj2_jesdn_RelSample_year,etaj1_jesdn_RelSample_year, etaj2_jesdn_RelSample_year, pTj1_2p5_jesdn_RelSample_year, pt_leadingjet_pt30_eta2p5_jesdn_RelSample_year, pTj2_2p5_jesdn_RelSample_year, mj1j2_jesdn_RelSample_year, dEtaj1j2_jesdn_RelSample_year, yj1_jesdn_RelSample_year, yj2_jesdn_RelSample_year, dPhiHj1_jesdn_RelSample_year, dyHj1_jesdn_RelSample_year, dPhij1j2_jesdn_RelSample_year, dPhiHj1j2_jesdn_RelSample_year, yj1_2p5_jesdn_RelSample_year, yj2_2p5_jesdn_RelSample_year, dPhiHj1_2p5_jesdn_RelSample_year, dyHj1_2p5_jesdn_RelSample_year, mj1j2_2p5_jesdn_RelSample_year, dEtaj1j2_2p5_jesdn_RelSample_year, dPhij1j2_2p5_jesdn_RelSample_year, dPhiHj1j2_2p5_jesdn_RelSample_year, mass4lj_jesdn_RelSample_year, pT4lj_jesdn_RelSample_year, mass4ljj_jesdn_RelSample_year, pT4ljj_jesdn_RelSample_year, mass4lj_2p5_jesdn_RelSample_year, pT4lj_2p5_jesdn_RelSample_year, mass4ljj_2p5_jesdn_RelSample_year, pT4ljj_2p5_jesdn_RelSample_year, etaj2_2p5_jesdn_RelSample_year;


///////////////////////////////////////////////////////////////////////
// Total unc. variables
Float_t         TauC_Inc_0j_EnergyWgt_jesup_Total, TauB_Inc_0j_pTWgt_jesup_Total, TauC_Inc_0j_EnergyWgt_jesdn_Total, TauB_Inc_0j_pTWgt_jesdn_Total;
int jet1index_jesup_Total, jet2index_jesup_Total, jet1index2p5_jesup_Total, jet2index2p5_jesup_Total, jet1pt_jesup_Total, jet2pt_jesup_Total, jet1pt2p5_jesup_Total, jet2pt2p5_jesup_Total, njets_pt30_eta4p7_jesup_Total, njets_pt30_eta2p5_jesup_Total, njets_pt30_eta4p7_jesdn_Total, njets_pt30_eta2p5_jesdn_Total;
int jet1index_jesdn_Total, jet2index_jesdn_Total, jet1index2p5_jesdn_Total, jet2index2p5_jesdn_Total, jet1pt_jesdn_Total, jet2pt_jesdn_Total, jet1pt2p5_jesdn_Total, jet2pt2p5_jesdn_Total;

float pTj1_jesup_Total, pt_leadingjet_pt30_eta4p7_jesup_Total, pTj2_jesup_Total, etaj1_jesup_Total, etaj2_jesup_Total, pTj1_2p5_jesup_Total, pt_leadingjet_pt30_eta2p5_jesup_Total, pTj2_2p5_jesup_Total, mj1j2_jesup_Total, dEtaj1j2_jesup_Total, yj1_jesup_Total, yj2_jesup_Total, mass4lj_jesup_Total, pT4lj_jesup_Total, mass4ljj_jesup_Total, pT4ljj_jesup_Total, dPhiHj1_jesup_Total, dyHj1_jesup_Total, dPhij1j2_jesup_Total, dPhiHj1j2_jesup_Total, yj1_2p5_jesup_Total, yj2_2p5_jesup_Total, mass4lj_2p5_jesup_Total, pT4lj_2p5_jesup_Total, mass4ljj_2p5_jesup_Total, pT4ljj_2p5_jesup_Total, dPhiHj1_2p5_jesup_Total, dyHj1_2p5_jesup_Total, mj1j2_2p5_jesup_Total, dEtaj1j2_2p5_jesup_Total, dPhij1j2_2p5_jesup_Total, dPhiHj1j2_2p5_jesup_Total, etaj2_2p5_jesup_Total;

float pTj1_jesdn_Total, pt_leadingjet_pt30_eta4p7_jesdn_Total, pTj2_jesdn_Total,etaj1_jesdn_Total, etaj2_jesdn_Total, pTj1_2p5_jesdn_Total, pt_leadingjet_pt30_eta2p5_jesdn_Total, pTj2_2p5_jesdn_Total, mj1j2_jesdn_Total, dEtaj1j2_jesdn_Total, yj1_jesdn_Total, yj2_jesdn_Total, dPhiHj1_jesdn_Total, dyHj1_jesdn_Total, dPhij1j2_jesdn_Total, dPhiHj1j2_jesdn_Total, yj1_2p5_jesdn_Total, yj2_2p5_jesdn_Total, dPhiHj1_2p5_jesdn_Total, dyHj1_2p5_jesdn_Total, mj1j2_2p5_jesdn_Total, dEtaj1j2_2p5_jesdn_Total, dPhij1j2_2p5_jesdn_Total, dPhiHj1j2_2p5_jesdn_Total, mass4lj_jesdn_Total, pT4lj_jesdn_Total, mass4ljj_jesdn_Total, pT4ljj_jesdn_Total, mass4lj_2p5_jesdn_Total, pT4lj_2p5_jesdn_Total, mass4ljj_2p5_jesdn_Total, pT4ljj_2p5_jesdn_Total, etaj2_2p5_jesdn_Total;





#endif
